#!/bin/bash

if [ "$1" == "compile" ];
then
  javac Destination.java MilageRedemptionApp.java MilesRedeemer.java
  java MilageRedemptionApp miles.txt 
elif [ "$1" == "clean" ];
then 
  rm *.class
else
  echo "Invalid option"
fi
