import java.util.*; //import all because 
import java.io.*;   //simplicity 
import java.lang.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author andrew
 */
public class GUIRedeemMiles extends javax.swing.JFrame {

    /**
     * Creates new form GUIRedeemMiles
     */
    public GUIRedeemMiles(){
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        ExploratoryPanel = new javax.swing.JPanel();
        CityListLabel = new java.awt.Label();
        RequiredMilesLabel = new java.awt.Label();
        UpgradeLabel = new java.awt.Label();
        SuperSaver_label = new java.awt.Label();
        Months_Label = new java.awt.Label();
        ReqMilesField = new javax.swing.JTextField();
        UpgradeMilesField = new javax.swing.JTextField();
        SuperSaverField = new javax.swing.JTextField();
        MonthsField = new javax.swing.JTextField();
        DestinationBox = new javax.swing.JComboBox<>();
        RedeemerPanel = new javax.swing.JPanel();
        UserMilesField = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        RedeemMilesButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        RedeemedMilesArea = new javax.swing.JTextArea();
        RemainingMilesLabel = new java.awt.Label();
        UserMilesLabel = new java.awt.Label();
        UserMonthLabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airline Milage Redemption");
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 300));
        setMinimumSize(new java.awt.Dimension(600, 300));

        ExploratoryPanel.setBackground(new java.awt.Color(51, 51, 51));
        ExploratoryPanel.setForeground(new java.awt.Color(255, 255, 255));

        CityListLabel.setText("List of Destination Cities");

        RequiredMilesLabel.setText("Required Miles");

        UpgradeLabel.setText("Miles for Upgrading");

        SuperSaver_label.setText("Miles for SuperSaver");

        Months_Label.setText("Months for SuperSaver");

        ReqMilesField.setEditable(false);
        ReqMilesField.setText("                     ");

        UpgradeMilesField.setEditable(false);
        UpgradeMilesField.setText("                     ");
        UpgradeMilesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpgradeMilesFieldActionPerformed(evt);
            }
        });

        SuperSaverField.setEditable(false);
        SuperSaverField.setText("                     ");
        SuperSaverField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuperSaverFieldActionPerformed(evt);
            }
        });

        MonthsField.setEditable(false);
        MonthsField.setText("                     ");
        MonthsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthsFieldActionPerformed(evt);
            }
        });

        DestinationBox.setModel(new javax.swing.DefaultComboBoxModel<>(cityNames));
        DestinationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExploratoryPanelLayout = new javax.swing.GroupLayout(ExploratoryPanel);
        ExploratoryPanel.setLayout(ExploratoryPanelLayout);
        ExploratoryPanelLayout.setHorizontalGroup(
            ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExploratoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExploratoryPanelLayout.createSequentialGroup()
                        .addComponent(CityListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ExploratoryPanelLayout.createSequentialGroup()
                        .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SuperSaver_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(RequiredMilesLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Months_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ExploratoryPanelLayout.createSequentialGroup()
                                .addComponent(UpgradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ExploratoryPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(DestinationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ExploratoryPanelLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SuperSaverField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MonthsField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExploratoryPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReqMilesField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpgradeMilesField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))))
        );
        ExploratoryPanelLayout.setVerticalGroup(
            ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExploratoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CityListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(DestinationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExploratoryPanelLayout.createSequentialGroup()
                        .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RequiredMilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReqMilesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpgradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpgradeMilesField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuperSaver_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuperSaverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExploratoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonthsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Months_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        RedeemerPanel.setBackground(new java.awt.Color(51, 51, 51));
        RedeemerPanel.setForeground(new java.awt.Color(255, 255, 255));

        UserMilesField.setText("                     ");
        UserMilesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMilesFieldActionPerformed(evt);
            }
        });

        RedeemMilesButton.setText("Redeem Tickets >>>");
        RedeemMilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedeemMilesButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("                     ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        RedeemedMilesArea.setEditable(false);
        RedeemedMilesArea.setColumns(20);
        RedeemedMilesArea.setRows(10);
        RedeemedMilesArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane2.setViewportView(RedeemedMilesArea);

        RemainingMilesLabel.setText("Your Remaining Miles");

        UserMilesLabel.setText("Your Accumulated Miles");

        UserMonthLabel.setText("Month of Departure");

        javax.swing.GroupLayout RedeemerPanelLayout = new javax.swing.GroupLayout(RedeemerPanel);
        RedeemerPanel.setLayout(RedeemerPanelLayout);
        RedeemerPanelLayout.setHorizontalGroup(
            RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RedeemerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RedeemerPanelLayout.createSequentialGroup()
                        .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RedeemerPanelLayout.createSequentialGroup()
                                .addComponent(RemainingMilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RedeemerPanelLayout.createSequentialGroup()
                                .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserMilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserMonthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserMilesField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RedeemerPanelLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RedeemerPanelLayout.createSequentialGroup()
                                .addComponent(RedeemMilesButton)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RedeemerPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );
        RedeemerPanelLayout.setVerticalGroup(
            RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RedeemerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserMilesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserMilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserMonthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RedeemMilesButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RedeemerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemainingMilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ExploratoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RedeemerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExploratoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RedeemerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserMilesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMilesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserMilesFieldActionPerformed

    private void RedeemMilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedeemMilesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RedeemMilesButtonActionPerformed

    private void UpgradeMilesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpgradeMilesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpgradeMilesFieldActionPerformed

    private void SuperSaverFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuperSaverFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuperSaverFieldActionPerformed

    private void MonthsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthsFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void DestinationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationBoxActionPerformed
        selectedDest = DestinationBox.getSelectedItem().toString();
        for(Destination d: dest){
          if(d.getName() == selectedDest){
            ReqMilesField.setText(String.valueOf(d.getMiles()));
            UpgradeMilesField.setText(String.valueOf(d.getUpgdeMiles()));
            SuperSaverField.setText(String.valueOf(d.getSaverMiles()));
            MonthsField.setText(String.valueOf(d.getStartMonth()) + " - " 
                                  + String.valueOf(d.getEndMonth()));
          }
        }
    }//GEN-LAST:event_DestinationBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         //break if argument list is too long or short
         if(args.length != 1) {
           System.out.println("Error: Invalid number of"
                              + " arguments.");
           return;
         }

    
         try{
     
           //variable block
           Scanner scan =
           new Scanner(new File(args[0])).useDelimiter(";|-");
           Scanner stdi = new Scanner(System.in);

           //instantiate Miles Redeemer class
           MilesRedeemer mrService = new MilesRedeemer();

           //pass scanner to read destinations method
           try{
             mrService.readDestinations(scan);
           }
           //catch the general exception
           catch(Exception ex){
           //catch general exception
             System.out.println(ex.getMessage());
            return;
           }
           
           //get city name array and array of destinations
          dest = mrService.getdestL(); 
          cityNames = mrService.getCityNames();
         }
         catch(FileNotFoundException fileE){
           //for files not found
           System.out.println(fileE);
           return;
         }



        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRedeemMiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRedeemMiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRedeemMiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRedeemMiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRedeemMiles().setVisible(true);
            }
        });
    }
    
    
    private static ArrayList<Destination> dest;
    private static String selectedDest;    
    private static String[] cityNames; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label CityListLabel;
    private javax.swing.JComboBox<String> DestinationBox;
    private javax.swing.JPanel ExploratoryPanel;
    private javax.swing.JTextField MonthsField;
    private java.awt.Label Months_Label;
    private javax.swing.JButton RedeemMilesButton;
    private javax.swing.JTextArea RedeemedMilesArea;
    private javax.swing.JPanel RedeemerPanel;
    private java.awt.Label RemainingMilesLabel;
    private javax.swing.JTextField ReqMilesField;
    private java.awt.Label RequiredMilesLabel;
    private javax.swing.JTextField SuperSaverField;
    private java.awt.Label SuperSaver_label;
    private java.awt.Label UpgradeLabel;
    private javax.swing.JTextField UpgradeMilesField;
    private javax.swing.JTextField UserMilesField;
    private java.awt.Label UserMilesLabel;
    private java.awt.Label UserMonthLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
